name: On pull request

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

jobs:
  rustfmt:
    name: Style & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install protoc
        run: ./scripts/install_protoc_linux.sh

      - uses: Swatinem/rust-cache@v2

      - name: rustfmt
        run: cargo fmt -- --check
      - name: Rigorous lint via Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -W clippy::unwrap_used

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        feature: [default, login]

    steps:
      - uses: actions/checkout@v2

      - name: Install protoc
        run: ./scripts/install_protoc_linux.sh

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose --features ${{ matrix.feature }}

      - name: Run Integration Tests
        run: ./run_test_sequentially.sh ${{ matrix.feature }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install protoc
        run: choco install protoc

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Build
        run: cargo build --verbose
