name: momento-cli version update pr-pull
on:
  pull_request_target:
    types:
      - labeled
jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'automation')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main
