name: test

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  APP_NAME: 'momento-cli'
  MAINTAINER: 'momentohq'
  DESC: 'Official CLI for Momento Serverless Cache'

jobs:
  update-winget-package-manager:
    runs-on: windows-latest

    steps:
      - name: Download winget
        run: iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe

      - name: Build installer URL
        id: build_installer_url
        env:
          VERSION: 0.26.5
        run: |
          $installerUrl = https://github.com/momentohq/momento-cli/releases/download/v$env:VERSION/momento-cli-$env:VERSION.windows_x86_64.msi
          echo $installerUrl
          echo "::set-output name=installer_url::$installerUrl"

      - name: Open PR on WinGet
        env:
          INSTALLER_URL: ${{ steps.build_installer_url.outputs.installer_url }}
          VERSION: 0.26.5
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "running .\wingetcreate.exe update momento.cli -s -v $env:VERSION -u $env:INSTALLER_URL -t env:GITHUB_TOKEN"
